---
title: "topicmodeling1.rmd"
author: "shuba"
date: "6/24/2021"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
library(tidytext)
library(readtext)
library(x13binary)
library(x12)
library(quanteda)

library(sparklyr)
```

```{r}
# text1 <- read.csv(file = 'A50002.P4.csv')
# 
# tidytxt1 <- text1 %>%
#     select(text)%>%
#     unnest_tokens(word, text) %>%
#     anti_join(stop_words) %>%
#     count(word, sort = TRUE)
```

```{r}

library(plyr)

setwd("~/Downloads")
mydir = "ethics_csv"
myfiles = list.files(path=mydir, pattern="*.csv", full.names=TRUE)
raw_data = ldply(myfiles, read_csv)

# raw_data <- read.csv(file = 'A50002.P4.csv')
# raw_data <- rbind(raw_data, read.csv(file = 'A50004.P4.csv'))

```

```{r}
rm(A50002_P4, all_data, all_text, ethics_sparse, raw_data1, raw_data2, raw_data3, sc, wordsonly2, wordsonly3)
```


```{r}
wordsonly <- raw_data %>%
  select(title, text) 

wordsonly <- wordsonly %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words)

# wordsonly %>%
#   count(word, sort = TRUE)

```

```{r}
words_dtm <- wordsonly %>%
  count(title, word) %>%
  cast_dtm(title, word, n)

library(topicmodels)

words_lda <- LDA(words_dtm, k = 16, control = list(seed = 1234))
words_lda
```

```{r}
text_topics <- tidy(words_lda, matrix = "beta")

top_terms <- text_topics %>%
  group_by(topic) %>%
  slice_max(beta, n = 5) %>%
  ungroup() %>%
  arrange(topic, -beta)

top_terms
```

```{r}
top_terms %>%
  mutate(term = reorder_within(term, beta, topic)) %>%
  ggplot(aes(beta, term, fill = factor(topic))) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ topic, scales = "free") +
  scale_y_reordered()
```


# ```{r}
# library(quanteda)
# library(stm)
# 
# ethics_dfm <- wordsonly %>%
#   count(title, word, sort = TRUE) %>%
#   cast_dfm(title, word,n)
# 
# topic_model <- stm(ethics_dfm, K=5,verbose=FALSE, init.type = "Spectral")
# ```
# 
# ```{r}
# library(reshape2)
# td_beta <- tidy(topic_model)
# td_beta %>%
#     group_by(topic) %>%
#     top_n(10, beta) %>%
#     ungroup() %>%
#     mutate(topic = paste0("Topic ", topic),
#            term = reorder_within(term, beta, topic)) %>%
#     ggplot(aes(term, beta, fill = as.factor(topic))) +
#     geom_col(alpha = 0.8, show.legend = FALSE) +
#     facet_wrap(~ topic, scales = "free_y") +
#     coord_flip() +
#     scale_x_reordered() +
#     labs(x = NULL, y = expression(beta),
#          title = "Highest word probabilities for each topic",
#          subtitle = "Different words are associated with different topics")

```
```{r}
# td_beta %>%
#     group_by(topic) %>%
#     top_n(10, beta) %>%
#     ungroup() %>%
#     arrange(topic, -beta)
# td_beta <- td_beta %>%
#   mutate(term = reorder(term, beta))%>%
#   ggplot(aes(term,beta,fill = factor(topic)))+
#   geom_col(show.legend = FALSE)+
#   facet_wrap(~ topic, scales = "free")+
#   coord_flip()
```



